-- Define which database you are using, may need to create new database
use testdb;

-- Drop the PETRESCUE table in case it exists
drop table if exists PETRESCUE;

-- Create the PETRESCUE table 
create table PETRESCUE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	COST DECIMAL(6,2),
	RESCUEDATE DATE,
	PRIMARY KEY (ID)
);

-- Insert sample data into PETRESCUE table
insert into PETRESCUE values 
	(1,'Cat',9,450.09,'2018-05-29'),
	(2,'Dog',3,666.66,'2018-06-01'),
	(3,'Dog',1,100.00,'2018-06-04'),
	(4,'Parrot',2,50.00,'2018-06-04'),
	(5,'Dog',1,75.75,'2018-06-10'),
	(6,'Hamster',6,60.60,'2018-06-11'),
	(7,'Cat',1,44.44,'2018-06-11'),
	(8,'Goldfish',24,48.48,'2018-06-14'),
	(9,'Dog',2,222.22,'2018-06-15')
;


SELECT * FROM petrescue;
-- COLS
-- ID
-- ANIMAL
-- QUANTITY
-- COST
-- RESCUEDATE


SELECT SUM(COST) AS SUM_COST FROM PETRESCUE;

SELECT MAX(QUANTITY) FROM PETRESCUE;

SELECT MIN(QUANTITY) FROM PETRESCUE;

SELECT AVG(COST) FROM PETRESCUE;

SELECT ROUND(COST) FROM PETRESCUE;

SELECT ANIMAL, LENGTH(ANIMAL) AS LEN FROM PETRESCUE;

SELECT UCASE(ANIMAL) FROM PETRESCUE;

SELECT LCASE(ANIMAL) FROM PETRESCUE;

SELECT DAY(RESCUEDATE) FROM PETRESCUE;
SELECT MONTH(RESCUEDATE) FROM PETRESCUE;
SELECT YEAR(RESCUEDATE) FROM PETRESCUE;

SELECT RESCUEDATE, DATE_ADD(RESCUEDATE, INTERVAL 5 DAY) AS ADDED_DAY FROM PETRESCUE;
SELECT RESCUEDATE, DATE_ADD(RESCUEDATE, INTERVAL -5 MONTH) AS ADDED_MONTH FROM PETRESCUE;
	-- NEGATIVES CAN BE USED TO SUBTRACT DATE OR MONTH

-- DOING THE NEGATIVE THING FORMALY
SELECT RESCUEDATE, DATE_SUB(RESCUEDATE, INTERVAL 5 DAY) AS SUB_DAY FROM PETRESCUE;
SELECT RESCUEDATE, DATE_SUB(RESCUEDATE, INTERVAL 5 MONTH) AS SUB_DAY FROM PETRESCUE;

SELECT DATEDIFF(CURRENT_DATE, RESCUEDATE) FROM PETRESCUE;

SELECT FROM_DAYS(DATEDIFF(CURRENT_DATE, RESCUEDATE)) FROM PETRESCUE;


-- PRACTICE PROBLEMS

SELECT ANIMAL, AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL = "DOG";

SELECT DISTINCT UCASE(ANIMAL) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE ANIMAL = "CAT";
SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL) = "cat";

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE) = "05";
SELECT SUM(QUANTITY), MONTH(RESCUEDATE) FROM PETRESCUE GROUP BY (MONTH(RESCUEDATE));

SELECT ID, DATE_ADD(RESCUEDATE, INTERVAL 1 YEAR) AS TARGET_DATE FROM PETRESCUE;












